### ISSUE TITLE
Talent Degrees not showing in full character sheet

### ISSUE THREAD

**Issue by Txus5012** [vkdolea/age-system#103]
Thanks for accepting my PR. There seems to be an issue with your implementation, tough.

The degree isn't shown in the full character sheet.
![Degrees](https://github.com/vkdolea/age-system/assets/87753744/f8cfd065-ac7a-4475-b2c2-9bfc40f53e88)

It is shown correctly in the block sheet.
Seen in v10.

**Comment by vkdolea** [comment]
It is now fixed on version 2.0.1
