### ISSUE TITLE
Issues opening Edit menu with Equipment and Powers on Character Sheet

### ISSUE THREAD

**Issue by JasonSunday** [vkdolea/age-system#106]
While trying edit a character's powers or Equipment, the right click menu closes right after it opens. If I can get it to stay open, it brings up the wrong menu when trying to edit the item.

I am on v11.

![Screenshot 2023-07-23 204525](https://github.com/vkdolea/age-system/assets/10623958/8fcf7344-1439-4511-8f6a-380eb234957d)
![Screenshot 2023-07-23 204431](https://github.com/vkdolea/age-system/assets/10623958/d33b15e8-6dc8-4af3-bc5b-94fbcfa84e17)

**Comment by varnoreberet** [comment]
I'm having a similar issue, it seems to happen after a server restart. The links to weapons, powers and focuses break, I think (other items seem unaffected, equipment that are not weapons works normally).  After a restart, if you try to edit or look at the item all that shows up is the image related to the item(like with the quarterstaff seen above). Also related to the first issue mentioned right-clicking on the image of the item works normally, but right-clicking anywhere else just closes it immediately. I'm also on v11.

**Comment by vkdolea** [comment]
I am working on this issue. Thanks for bringing it to my attention!

**Comment by vkdolea** [comment]
I didn't have enough time to track WHY this problem was happening, however on new Foundry VTT version v11 buil 308 this problem seems to be fixed. I assume this was an API issue.

The "vanishing" context menu is now fixed, and it was a real issue with my code.

I am closing this ticket now.

**Comment by varnoreberet** [comment]
Looks like it is still using the wrong sheet after a refresh, even on version 11 308.
