### ISSUE TITLE
Willpower Skill Focus doesn't show

### ISSUE THREAD

**Issue by roninjedi78** [vkdolea/age-system#107]
![image](https://github.com/vkdolea/age-system/assets/14360370/1b9d51e4-dfb2-4f67-be36-b7fe2b90240b)
Skill focuses on Willpower do not show up. This is both full and block mode. 

If the same focus is added a second time I get the error: Focus is not added to character - it already owns a Focus named "SELF-DISCIPLINE"

So its there as far as the code is concerned, but the UI is not displaying it.

**Comment by vkdolea** [comment]
Hi! I tested on my end adding SELF-DISCIPLINE as a Willpower focus and it worked fine. Could you confirm the no modules are active when you experience this issue? Also, you could also hit F12 and print the latest messages from console log.

**Comment by roninjedi78** [comment]
So I created a brand new world, made a test actor and test focus and...it shows. 

So whatever is causing the bug must be specific to that World. .....i'll begin the process of migrating my items/journals/etc over to the new world I created and see if any of them break it again LOL.

**Comment by vkdolea** [comment]
Oh boy... it seems you got your previous world corrupted. I hope you are able to port everything to a healthy world!

I will close the ticket now, but you can re-open it if the problem returns.
