### ISSUE TITLE
(Dragon Age) Manna is not reduced for additional spell strenght spend

### ISSUE THREAD

**Issue by remyke** [vkdolea/age-system#112]
Heal for example can be boosted.

_Your touch seals wounds and restores vigor to one wounded target. You can choose to spend up to 3 mana points when you cast this spell. For each mana point spent, the target gets back 1d6 Health. You can cast this on yourself._

**Comment by vkdolea** [comment]
Option added. It will appear as option in the next updated when right-clicking the button to roll Powers.
