### ISSUE TITLE
(Dragon Age) Warning on custom active effects

### ISSUE THREAD

**Issue by remyke** [vkdolea/age-system#113]
Open a character sheet on the effects tab where a custom active effect is added and the console gets this warning

> commons.js:2007 Error: You are accessing ActiveEffect#label which has been migrated to ActiveEffect#name
> Deprecated since Version 11
> Backwards-compatible support will be removed in Version 13
>     at logCompatibilityWarning (commons.js:1996:19)
>     at ActiveEffect._logDataFieldMigration (commons.js:8442:14)
>     at Object.get (commons.js:8406:18)
>     at lookupProperty (handlebars.min.js:27:16153)
>     at eval (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:11:250)
>     at Object.h [as fn] (handlebars.min.js:27:17870)
>     at Object.<anonymous> (handlebars.min.js:27:10117)
>     at Object.c (handlebars.min.js:27:19853)
>     at eval (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:15:47)
>     at h (handlebars.min.js:27:17870)
>     at c (handlebars.min.js:27:6899)
>     at Object.<anonymous> (handlebars.min.js:27:7289)
>     at Object.c (handlebars.min.js:27:19853)
>     at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:25:49)
>     at c (handlebars.min.js:27:15429)
>     at d (handlebars.min.js:27:15744)
>     at e (handlebars.min.js:28:22748)
>     at Object.h (handlebars.min.js:27:18738)
>     at Object.c [as invokePartial] (handlebars.min.js:27:15036)
>     at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:145:28)
>     at c (handlebars.min.js:27:15429)
>     at d (handlebars.min.js:27:15744)
>     at e (handlebars.min.js:28:22748)
>     at renderTemplate (foundry.js:7663:10)
>     at async ageSystemSheetCharAlt._renderInner (foundry.js:5895:16)
>     at async ageSystemSheetCharAlt._renderInner (foundry.js:6463:18)
>     at async ageSystemSheetCharAlt._render (foundry.js:5740:19)
>     at async ageSystemSheetCharAlt._render (foundry.js:6452:5)

**Comment by vkdolea** [comment]
This issue is already fixed. Ready for the next release.
