### ISSUE TITLE
 The system's style forces every single font in the game to be roboto (module Polyglot).

### ISSUE THREAD

**Issue by Snarfaxi** [vkdolea/age-system#125]
Hey, I added the mod [Polyglot](https://github.com/mclemente/fvtt-module-polyglot) but noticed that none of the fonts were working as they should. Apparently it's because [this line](https://github.com/vkdolea/age-system/blob/workspace/styles/age-system.css#L4215) is forcing every font to be Roboto. Is there a way to work around this so I can use the mod? It would be a fun way to let the players use their characters' different language skills. I tried to look around here but the only one talking about fonts was [this post](https://github.com/vkdolea/age-system/issues/66), but I have no knowledge of coding so didn't get any wiser.

**Comment by kamil-merdanov** [comment]
Have you tried deleting" !important"? If it doesn't help or the result will be improper, you can insert it back.

**Comment by vkdolea** [comment]
Adressed. It will be reflected in the next release.
