### ISSUE TITLE
Applying Wounded effect on The Expanse causes the sheet to bug

### ISSUE THREAD

**Issue by Imposator** [vkdolea/age-system#126]
One of my players applied the effect "Wounded" on his token after a fight but no couldn't open the sheet after that and it was impossible to remove the malus occured by the effect.
We had to export data from the sheet, remove the part where the effect is applied in the code structure then import datas to have the sheet work properly.

Here are the datas before applying any effect : 
[data before wonded.json](https://github.com/vkdolea/age-system/files/14152404/data.before.wonded.json)

When applying by changing the token, the sheet wont open anymore and the effect is not applied to rolls. Here are the datas of the sheet.
[data after wounded (token).json](https://github.com/vkdolea/age-system/files/14152418/data.after.wounded.token.json)
![image](https://github.com/vkdolea/age-system/assets/77997931/d34c0952-fe93-4aa2-9492-5c3d982ffc0c)

When applying the effect by the effects tab, the rolls are correct but the token is not modified (no icon is showing the wounded effect)
![image](https://github.com/vkdolea/age-system/assets/77997931/e7623df4-b887-4a84-b048-4dcc12d7339e)
And the sheet wont open anymore.
[data after wounded (sheet).json](https://github.com/vkdolea/age-system/files/14152428/data.after.wounded.sheet.json)
The effect tab dont show anything as if no effects had been applied.
![image](https://github.com/vkdolea/age-system/assets/77997931/e1a22e72-6d32-4a97-a2c6-0adb475edf72)

For your perfect information, I'm playing on The Forge with a V10 (last patch applied).

**Comment by vkdolea** [comment]
Closed. It will be effective in the next release.
