### ISSUE TITLE
Keys and Variables

### ISSUE THREAD

**Issue by kamil-merdanov** [vkdolea/age-system#128]
Hello there and thank you for the AGE-System! 

For some reason the `system.attackMod` key doesn't work via conditions lib.
![blinded-penalty](https://github.com/vkdolea/age-system/assets/157103190/1d0997ca-ece0-44fd-9de6-946f282613c7)
The same goes for `system.dmgMod`. `system.testMod` on the other hand works just fine.

Variables don't work unless you type `@abilities.abl.value`.

**Comment by vkdolea** [comment]
I am sorry, but I could not reproduce these issues. All mentioned Active Effects worked as expected when used on Conditions Workshop. Maybe there is something related to conflict with another modules?

**Comment by vkdolea** [comment]
Thanks and no problem! I'm glad you figured it out
