### ISSUE TITLE
Armor and Penalty modifiers no longer working

### ISSUE THREAD

**Issue by SPConlin** [vkdolea/age-system#129]
While adding Armor to the items to prepare for a Modern AGE game, I noticed that the Armor values and penalties are no longer populating on the character sheets. I checked that the modifiers were set and turned on and that the armor was active. This is effecting both Modern AGE and Fantasy AGE. I have checked the functionality using Edge and Chrome. I'm not seeing any errors in the console.

![image](https://github.com/vkdolea/age-system/assets/7864940/eb1e3849-95bf-4f91-a494-624e5e6ce3b9)

![image](https://github.com/vkdolea/age-system/assets/7864940/61e5b81f-a522-4d13-a1c7-1914d3e08cb4)

**Comment by SPConlin** [comment]
Some additional testing and it appears that none of the modifiers are being applied to the character sheets. I tried using items and powers with health, armor, and ability modifiers.

**Comment by vkdolea** [comment]
Thanks for pointing that out! Version 2.0.5 already released to fix this bug.
