### ISSUE TITLE
Editor for Character-Features is unusable on Firefox.

### ISSUE THREAD

**Issue by Doppelnull** [vkdolea/age-system#33]
The editor for the Chareacter-Features (below Drive, Quality and Downfall) is too small to use on Firefox (see first screenshot). Setting a min-height of about 100px for the enclosing div fixes this behaviour (see second screenshot).

![editor default](https://user-images.githubusercontent.com/14310332/111086996-85c9b000-851f-11eb-916f-938a83e534ae.png)

![Editor fixed](https://user-images.githubusercontent.com/14310332/111086998-86624680-851f-11eb-9ed3-561e474487dd.png)

**Comment by vkdolea** [comment]
Thanks for you comment. Could you shate the code snippet, so I can fully understand your suggestion? I will add this fix in the next revision.
