### ISSUE TITLE
hasPlayerOwner not set correctly on items

### ISSUE THREAD

**Issue by schlosrat** [vkdolea/age-system#41]
I noticed this in the expansion of an item I'd previously created using the system normal Create Item interface. This looks like it might be indicating a bug or possibly a missing bit of something. The hasPlayerOwner field for the item I was inspecting reads "Exception: TypeError: Cannot read property 'default' of undefined at ageSystemItem.get hasPlayerOwner [as hasPlayerOwner] (https://localhost/scripts/foundry.js:29367:30) at ageSystemItem.invokeGetter (<anonymous>:1:142)]". Granted this example is on an NPC sheet, but I get the same thing on items that are on a sheet for an actor owned by a player.

Also, I've noticed that the actor structure is populating the isPC attribute which is triggering a warning in the console stating that "The Actor#isPC attribute has been deprecated in favor of the more general Entity#hasPlayerOwner attribute". perhaps this is related?

**Comment by vkdolea** [comment]
#hasPlayerOwner is the the method in use, as #isPC will be discontinued in future FoundryVTT releases. This method is expected to be used with Actors only. Looking at Item class documentation, #hasPlayerOwner is not even listed. I believe it could be a bug on FoundryVTT version 0.7.9.
