### ISSUE TITLE
Add GM Roll for Weapons, Talents, etc

### ISSUE THREAD

**Issue by jaythegreenling** [vkdolea/age-system#49]
At the moment one can only whisper ability-based rolls, attacks, and damage. Would be neat to be able to whisper everything that's on a sheet.

Thanks for your work!

**Comment by vkdolea** [comment]
For now, Item rolls will be self-rolls when Shift is pressed. I will try adding more options in the future for this kind of messages.

**Comment by vkdolea** [comment]
Version 0.7.6 will implement item rolling respecting the option selected on chat box. Shift + Click will override this option and will trigger a self roll.
