### ISSUE TITLE
Add GM option to always roll using chat setting

### ISSUE THREAD

**Issue by MBraedley** [vkdolea/age-system#52]
As GM, I want to be able to roll dice always using the setting in chat.  I don't want to have to think about holding shift every time I want to roll some dice, especially since my chat window is telling me that the roll will be private (even though it really isn't).  Also, it's a lot easier to make private rolls public, but it's a bit hard putting the toothpaste back in the tube, as it were.

Please add an option to use the chat setting for all rolls made by the GM instead of defaulting to public when not rolling from chat.

**Comment by vkdolea** [comment]
Hi! Thanks for your suggestion! You will be glad to hear that I just released version 0.7.2 with this functionality. I tested lots of rolls and it seems to be working as expected. Please revert with comments if you find a bug.
