### ISSUE TITLE
Invalid BaseTexture errors for AgeSystem effects using SVG files on Firefox

### ISSUE THREAD

**Issue by Ilysssa** [vkdolea/age-system#63]
## Expected behaviour
The icons should appear as normal, and apply its effects correctly.

## Current behaviour
When a system-specific condition is added to a token, the icon does not appear on the token. Furthermore, it renders the token unresponsive, and sometimes completely non-interactive. If the effect is added to a token with a linked actor, this also causes any tokens placed onto the canvas using that actor to become unresponsive and non-interactive, requiring you to delete the effects using the developer console. 

The error in the Dev Console:
![The error in the Dev Console](https://user-images.githubusercontent.com/57351685/131318578-3a584e90-e541-4968-8c53-0846ef2ff4e2.jpg)

Example of behaviour in Firefox:
![Example of behaviour in Firefox](https://user-images.githubusercontent.com/57351685/131317344-77c9d36c-fc71-4e7a-8266-5046b8a885e8.jpg)

Example of correct behaviour using a different browser (Brave):
![Example of behaviour in Brave](https://user-images.githubusercontent.com/57351685/131316783-f9d599be-b244-4983-a253-8c0d20c9a8e8.jpg)

## Possible Solution
After some troubleshooting, I found out that Firefox is very picky about how SVG files are formatted. The how's and the why's are beyond me, but I did manage to edit the SVG files to function correctly on Firefox. I am attaching a working example to this issue.

## Steps to reproduce 
1. Use Firefox as your browser
2. Add conditions to a token using the right-click conditions menu.
3. Add 'defeated' condition to a token using the combat tracker (skull icon).

## Context
From what I can tell, this primarily affects tokens that are currently on the canvas, or that are placed onto the canvas while their linked actors prototype token has any of these conditions. The numbered PNG files work as intended, this error only occurs with the effects that have SVG files. The default token icon (sensousness.svg) also breaks any token placed onto the canvas. However, the SVG files do appear correctly on the character sheets without any issues, and the dice-roller button is also working as intended.

## Possible Implementation
[acrobatic.txt](https://github.com/vkdolea/age-system/files/7075486/acrobatic.txt)

**Comment by vkdolea** [comment]
Thanks for bringing it to my attention. I will review SVG files at a later stage. I also would like to point that Firefox has a series of styling issues with Foundry. If possible, I would recommend using a different browser.

**Comment by vkdolea** [comment]
Fixed SVG files used in the core AGE System.
