### ISSUE TITLE
Multiple Focus modifiers cancel out

### ISSUE THREAD

**Issue by chligget** [vkdolea/age-system#65]
Per character, focus mods don't apply when there are multiple focus modifiers active at same time. If there are 2 or more focus mods (does not matter if the mods affect the same focus or not) active on a character, then neither mod will be considered as part of the skill roll. Turning focus mods off and leaving only 1 active restores the intended effect.

Also, it would be nice to able to add more than Focus modifier to a single item. i.e. a magic sword that gives +1 to Stamina and +1 to Might.

Thank you for putting all of this together and continuing to maintain and improve it!!

**Comment by vkdolea** [comment]
I can not commit on adding multiple stances of Focus bonus to a single item (at least by now), but I'll definitely fix the issue prevent bonuses from multiple items not working together.

**Comment by vkdolea** [comment]
Focus bonus from multiple items fixed. It will working in the next release.
