### ISSUE TITLE
Font Conflict (w/module Token Mold)

### ISSUE THREAD

**Issue by chligget** [vkdolea/age-system#66]
Found a conflict with the module Token Mold, but I've also found the source. Token Mold uses font-awesome to for stat overlays, but in the age-system.css at line 3694 the font-override styling causes these icons to show as errors. I was able to fix this particular issue by adding the '.fas' class to to *:not(i, .fas).

I have not found any other issues regarding font conflicts, but I'm sure you can think of a better solution.

**Comment by vkdolea** [comment]
Thanks for reporting. The solution you proposed is the best I can think of. It will be implemented in the next release.
