### ISSUE TITLE
Make Aim a property of Focus

### ISSUE THREAD

**Issue by schlosrat** [vkdolea/age-system#71]
Please make Aim a property of a focus item so that one can define focuses that use it and those that don't, where a focus that uses it will "consume" the Aim (rolling that focus will add the bonus from Aim, and then un-check Aim). It should be possible to have focuses that don't benefit from Aim.

It would also be nice if attribute rolls didn't benefit from Aim. If a roll is needed that's a straight attribute roll which should legitimately benefit from Aim, then it could probably be made using a weapon roll from the character sheet.

**Comment by vkdolea** [comment]
It makes sense!

1. Add a "attack" flag on Focus, so it will benefit from `Aim` when rolled
2. Attack rolls take benefit from `Aim`
3. After attacking with `Aim` it will be unchecked (it already happens after a normal Attack Roll)

The missing use case would be someone one attack directly from a Attribute. I could add a box on test options (the one opening when you left click a roll button) to indicate if the roll is an Attack.

Thanks for your suggestion.

**Comment by vkdolea** [comment]
Hi! I will change how combat maneuvers are automated. I will close this issue, as it will not be relevant in the next dev cycle.

Cheers!
