### ISSUE TITLE
Hide applied Damage output

### ISSUE THREAD

**Issue by wurstkenner69** [vkdolea/age-system#72]
please make an option to disable the animation where all players see the applied damage, so they dont know how much armor the actor has

**Comment by vkdolea** [comment]
Noted!

Tentative: I will try to add "??" instead of the value when damage/healing is applied on tokens not owned by players.

**Comment by vkdolea** [comment]
When damage/healing is applied to a token, only players with Observer and Owner permissions will see the floating damage. This change will go live on version 0.12.0. Also know as "the next one".
