### ISSUE TITLE
(Dragon Age) Problem with Heal

### ISSUE THREAD

**Issue by ZeeRrk** [vkdolea/age-system#77]
Hi,
When i create a spell who heal mates, the spell do damage and not Healing.

I put some screenshot.

Thanks to read me, it's not an urgency, 

![Problem Heal](https://user-images.githubusercontent.com/112800452/188304910-b7b804c3-7b65-4c6f-958b-db9507026cc3.png)
![Problem Heal 2](https://user-images.githubusercontent.com/112800452/188304913-75ec4f7b-379e-42df-94b0-a5f9fa476f36.png)

**Comment by vkdolea** [comment]
Instead of clicking the button on chat card, right click the cjat card to open context menu. Select "heal" option to geal selected tokens.

You can use this method with all roll chat cards

**Comment by ZeeRrk** [comment]
Oh nice, i didn't see it.

Thanks you for this ! 

you do a great job with this, really thanks !
