### ISSUE TITLE
Spaceship (and Vehicle) sheet resizeable? + Shaceship weaponcard damagefield issue 

### ISSUE THREAD

**Issue by Alis-72** [vkdolea/age-system#81]
Would it be possible to make spaceship & vehicle sheets resizeable like charactersheet?
Also noticed that itemtype SpaceshipFeature->MopuntedWeapon->Damage field does not accept characters (i.e. cannot type 2d6), accepts only numbers.

**Comment by vkdolea** [comment]
Thanks for report the problem and adding a suggestion! Damage card fix and resizing damages are now possible, starting on version 1.1.7.
