### ISSUE TITLE
Armor Training Master & penetrating damage

### ISSUE THREAD

**Issue by wurstkenner69** [vkdolea/age-system#84]
The Master degree in the armour training talent allows you to only take piercing (half) damage when the dealt damage is penetrating. It would be really nice to make it easier in the system to calculate that damage automatically without changing the spells i have already implemented with penetrating damage. I think it would be relatively easy to add this: when an actor gets damage, the option at "Armor Piercing" (Half Armor) overrides the pre configured penetrating damage. So even if the damage is penetrating, by checking that box the damage still counts half your armor.

**Comment by vkdolea** [comment]
Hi! I have no plans to add automation to detect penetration statuses of attacks versus armor or talents worn by actors. However, the interface used to apply damage to tokens has a solution to consider full armor, total armor or no armor. I hope it works for know. 

![image](https://user-images.githubusercontent.com/66521243/210879631-d8543bca-fd1b-4f0b-bfc0-cc6ace502e73.png)
