### ISSUE TITLE
Bug with Healing and Max Health 

### ISSUE THREAD

**Issue by Calistocrates** [vkdolea/age-system#85]
Observed this issue yesterday:

Healing applied through right clicking a roll output or a breather seems to always treats the manually input Health MAX value as the definite maximum. It does not adjust for for maximum health bonuses applied from items or talents or anything. 

For example, a character with 10 base health maximum, and +5 bonus health maximum, for 15 health max total.
100 pts of healing applied.
The character's health is only raised to 10, not 15 like you'd expect.

Thanks for the work so far. o7

**Comment by vkdolea** [comment]
Thanks for bringing it up! The problem is identified and fixed. Next version (by end of January) will have the bug corrected.

**Comment by Calistocrates** [comment]
Sweet! Thanks again!
