### ISSUE TITLE
Ship Quality (Flaw) does not work

### ISSUE THREAD

**Issue by KaiderWeise** [vkdolea/age-system#86]
I would like to implement this effect: "The ship is not as structurally sound as it should be (or perhaps, once was); reduce its Hull score to that of the Size category one below the ship’s Size."
My spaceship is size Large, which brings 2d6 hull. Because of the Fragile flaw, it drops to the level before it, which is 1d6.

![image](https://user-images.githubusercontent.com/78543670/204148563-55875192-4daa-4ea5-b4ce-95a89b797117.png)

The "-1" does not work, but I can only enter numbers in this field.

**Comment by vkdolea** [comment]
This function will be working fine in the next release. I will close this issue now. Thanks for reporting!
