### ISSUE TITLE
Feature Request: Roll Result Cards should have Token Name, instead of Actor Name

### ISSUE THREAD

**Issue by r2roberts** [vkdolea/age-system#91]
If there are several tokens for the same Actor, the Roll Result cards display the same actor name. I can't tell which token which card refers to.

BTW, I love the work you've done. Great Job.

**Comment by r2roberts** [comment]
Maybe they should have "ActorName(TokenName)" on the results card, in order to have both.

**Comment by vkdolea** [comment]
Hi! I was looking at this case, but I failed to identify a case where this situations arises. When I roll an Item from token sheet, I got token name  on chat card. Could you describe the steps to replicate this issue? I will be happy to fix it!

**Comment by r2roberts** [comment]
Ok. Create an NPC. Drag it on to the map twice. Change the token names to be different. Open one token and roll a test. Close it. Open the other and roll a test. Notice the roll result cards both refer to the actor name, and not the changed token names.

**Comment by r2roberts** [comment]
![Uploading Untitled.jpg…]()

**Comment by r2roberts** [comment]
![Untitled](https://user-images.githubusercontent.com/5421706/229381796-efd980cc-8de9-4247-a20a-695fcb2a4652.jpg)

**Comment by vkdolea** [comment]
Noted. I am fixing it now.

**Comment by r2roberts** [comment]
Thanks!
