### ISSUE TITLE
Confusion with Character Sheets

### ISSUE THREAD

**Issue by meenanox** [vkdolea/age-system#93]
Hi there,

Im pretty novice with this entire system - however I noticed on a glance over (and even after changing the system to Dragon AGE) there is no spot for Mana Points / MP. I can see Power Points but i'm not entirely sure (as i've never used normal AGE) if that is the usual stand in.

Is there something i'm not doing correctly?

**Comment by vkdolea** [comment]
Hello @meenanox! Mana (Dragon AGE), Kana (Threefold) and Spell Points (Fantasy AGE) are different names for Power Points (Modern AGE).

Adding an option to set the correct name of this resource is for a long long time in my TODO list.

Maybe I can add it on next update? I will keep this issued opened to track it.

**Comment by meenanox** [comment]
I'd really appreciate that.
There is a lot of stuff that doesnt fully correlate. but if it is difficult then,  I understand if it isnt too important!

**Comment by vkdolea** [comment]
Changes executed. They will be presented in the next revision. A new System Setting was created to change Power flavor.
