### ISSUE TITLE
foundry hud weblate

### ISSUE THREAD

**Issue by eunaumtenhoid** [vkdolea/age-system#95]
hi, is it possible to add your mods to foundry hud weblate for us to translate or update the translation faster? https://weblate.foundryvtt-hub.com/

**Comment by vkdolea** [comment]
You can help translating usig gitLocalize, as explained [here](https://github.com/vkdolea/age-system/wiki/Localization). If you are looking for Portuguese localization (your user name gives it away) you don't need to worry, as I am the one adding Brazilian Portuguese localization.
