### ISSUE TITLE
New AGE Roller icon not visible if using black scene background color.

### ISSUE THREAD

**Issue by ProtonCrosser** [vkdolea/age-system#96]
The new AGE roller icon is nice but if a scene has a black background, it is not visible. Although the workaround is to not use a black background on scenes, this is sometimes preferable for scenes that take place at night, underground, or other dark environments. 

Request that the icon be adjusted to that it is visible with scenes using a black background.

**Comment by vkdolea** [comment]
I changed colors to match Macro bar and tested with white and black backgrounds. I hope you like it!

**Comment by ProtonCrosser** [comment]
Updated and it looks great. Thanks for the quick response.
